const express=require('express')
const app=express()
const db=require('./database/db')
const morgan=require('morgan')
const cors=require('cors')
const BodyParser=require('body-parser')
const FacultyRoute=require('./Routes/Faculty.routes')
const ModuleRouter=require('./Routes/Module.routes')
const LecturerRouter=require('./Routes/Lecturer.routes')
app.use(cors())
app.use(express.json())
app.use(BodyParser.urlencoded({extended: false}))
app.use(morgan('tiny'))
app.use('/faculty',FacultyRoute)
app.use('/subject',ModuleRouter)
app.use('/lecturer',LecturerRouter)
module.exports=app